---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  endpoint:
    # If we don't set services, crossplane hangs trying to validate the
    # credentials despite having skip_credentials_validation set to true
    services:
      - ec2
      - kms
      - rds
    # Within localstack, all services are available behind localhost.localstack.cloud
    # and this is the only name exposed via ingress
    hostnameImmutable: true
    url:
      type: Static
      static: "https://localhost.localstack.cloud"

  credentials:
    source: Secret
    secretRef:
      name: localstack-aws-token
      namespace: crossplane-system
      key: credentials

  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_requesting_account_id: true
  s3_use_path_style: true